force-app/main/default/objects/Qst_Survey_Result__c/Qst_Survey_Result__c.object-meta.xml
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <label>Qst_Survey_Result</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Custom Object Label Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Qst_Survey_Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Qst_Survey_Result__c/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ContactId</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Qst Survey Result (ContactId)</relationshipLabel>
    <relationshipName>Qst_Survey_Result1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Qst_Survey_Result__c/fields/Question_Text__c.field-meta.xml
<CustomField>
    <fullName>Question_Text__c</fullName>
    <label>Question Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Qst_Survey_Result__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Qst_ProducerSurveyUtil.cls
global class Qst_ProducerSurveyUtil {

	private Integer heapSizeLimit;
  	private String errMsg_heapSize;
	private List<Qst_Survey_Result__c> surveyResultList_c = new List<Qst_Survey_Result__c>(); 
	private List<SurveyResult> surveyResultList = new List<SurveyResult>();
	private String contactId;
	  
       webService static String testAction(String xmldata, String contactId) {
		String str = 'Action execute:';
		System.debug('### FLEX Action - '+xmldata);
		// Parse XML data here and save to SFDC
    	
    	Qst_ProducerSurveyUtil psu = new Qst_ProducerSurveyUtil();		
		psu.processXML(xmldata, contactId);
		
		return str;
       }
       
       
  //-----------------------------------------------------------------------------//
  // Parse input file
  //-----------------------------------------------------------------------------//
  public String processXML(String xmlString, String cid) {
    XmlStreamReader xsr = new XmlStreamReader(xmlString);
		this.heapSizeLimit = Limits.getLimitHeapSize();
    	this.errMsg_heapSize = 'Too much data to upload. Please try with less data to upload.';
    this.contactId = cid;
    while (xsr.hasNext()) {
      if (xsr.getLocalName() == 'question' && xsr.getEventType() == XmlTag.START_ELEMENT) {
        // Throw exception if heap size limit may be reached
        if (Limits.getHeapSize() > heapSizeLimit)
          throw new ClassException(errMsg_heapSize);
        
        surveyResultList.add(getSurveyResult(xsr));
      }
      xsr.next();
    }
    String out_err = '';
                            
    if (surveyResultList_c.size() > 0)
        insert surveyResultList_c;
    
    return out_err;
  }       

  //-----------------------------------------------------------------------------//
  // Make MPN_Survey_Result__c objects from data of XML file
  //-----------------------------------------------------------------------------//
  private SurveyResult getSurveyResult(XmlStreamReader xsr) {
    Qst_Survey_Result__c surveyResult_c = new Qst_Survey_Result__c();
    SurveyResult surveyResult = new SurveyResult(surveyResult_c);
    
    while (xsr.hasNext()) {
      if (xsr.getLocalName() == 'question' && xsr.getEventType() == XmlTag.END_ELEMENT) {
        	break;
      }
      
      if (xsr.getLocalName() == 'questionText' && xsr.getEventType() == XmlTag.START_ELEMENT) {
          xsr.next();
          if (xsr.getEventType() == XmlTag.CHARACTERS) {
          	surveyResult_c.Question_Text__c = xsr.getText();
          }
      }  
      if (xsr.getLocalName() == 'answers' && xsr.getEventType() == XmlTag.START_ELEMENT) {
          xsr.next();
          if (xsr.getEventType() == XmlTag.CHARACTERS) {
          	surveyResult_c.Rating__c = xsr.getText();
          }
      }  
              
      xsr.next();
    }
    System.debug('### XML parsing Contact ID - '+this.contactId);
    surveyResult_c.ContactId__c = this.contactId;
    surveyResultList_c.add(surveyResult_c);
    return surveyResult;
  }

// private exception class
  private class ClassException extends Exception {}
  
	private class SurveyResult {
    	private Qst_Survey_Result__c surveyRes;
    
    	public SurveyResult(Qst_Survey_Result__c custRes) {
      		this.surveyRes = custRes;
    	}
       
    	public void setSurveyRes(Qst_Survey_Result__c custRes) {
      		this.surveyRes = custRes;
    	}
    
    	public Qst_Survey_Result__c getSurveyRes() {
      		return this.surveyRes;
    	}
  }

}